### PR TITLE
Added shim for new spec support

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Checked on ie10 virtual machine. Works fine :)

**Comment by TrySound** [comment]
Maybe better use own implementation of these methods? Code will be smaller.

**Comment by TrySound** [comment]
Do not merge till I squash, please.

**Comment by jwilsson** [comment]
HI!
Sorry for the late reply.

I'm a bit unsure whether we want to do it like this. It just seems like we're adding unnecessary bytes. I'm thinking we could use the same test for support but use our implementation if it fails (i.e. if multiple arguments to `add()`/`remove()` isn't not supported we just use our methods for it instead).

**Comment by TrySound** [comment]
@jwilsson DOMTokenList constructor doesn't add `element` and `prop`. So i haven't idea, how to use our  implementation.

**Comment by jwilsson** [comment]
Ah, right. But some of the tests are failing for me in IE, could you test it again on your end? Could you also include `partial.js` in the tests so we're sure it's tested?

And while we're at it, could you rename `partial.js` to something like `DOMTokenList -shim.js`? :)

**Comment by TrySound** [comment]
`DOMTokenList-newest.js` ?

**Comment by jwilsson** [comment]
Yeah, we'll call it that for now. We can always change it later :)

**Comment by jwilsson** [comment]
Awesome, all tests seem to check out.

Could you just squash and we're good to go!

**Comment by TrySound** [comment]
@jwilsson Done!

**Comment by jwilsson** [comment]
Awesome!

BTW, if you want to, feel free to add yourself to `contributors` in `package.json` and `authors` in `bower.json`. I'll hold off publishing `1.1.0` for a few days so you can add yourself. Just commit it straight to `master`, no need for a PR or anything.

**Pull request merged**
