### PR TITLE
Aggressive minification

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by jwilsson** [comment]
Nice job!

However, some tests seems to be failing in at least IE11. Mind taking a look?

**Comment by TrySound** [comment]
Wrote tests for newest. Found error :) Fixed.

**Comment by jwilsson** [comment]
Awesome!

Thanks for the hard work, released in `1.1.0` :)

**Comment by TrySound** [comment]
Publish on npm

**Comment by jwilsson** [comment]
Published!

Sorry!

**Pull request merged**
