### PR TITLE
adding polyfill for SVGElement.prototype.classList

### PR DESCRIPTION
**Pull request by rodneyrehm**
In IE10 and IE11 `classList` does not exist and `className` is not a [DOMTokenList](https://developer.mozilla.org/en/docs/Web/API/DOMTokenList) but [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString). This PR provides the polyfill method to provide `classList` based on that.

If merged, the PR #13 is irrelevant (as included in another commit) - sorry for the confusion.

### CODE REVIEW

**Comment by jwilsson** [comment]
Looks great, thank you!

On a side note, you aren't interested in maintaining this? Or you, @TrySound?

**Comment by rodneyrehm** [comment]
> On a side note, you aren't interested in maintaining this?

I already have a few projects waiting for some love, so I'd rather not add another one. Judging by your question, I'm sure you understand…

**Comment by TrySound** [comment]
@jwilsson I can help with responses on issues, prs.

**Comment by rodneyrehm** [comment]
Would you be so kind to tag and release a new version after deciding if you want to include #15 or not? [v1.1.1](https://github.com/jwilsson/domtokenlist/releases/tag/v1.1.1) is kinda old… :)

**Pull request merged**
